config/routes.rb
Rails.application.routes.draw do
  resources :links, only: [:index, :create]
  root 'links#home_page'

  get 'links/:shortened_hash', to: 'links#show', as: 'show_link'
  get '/:shortened_hash', to: 'links#redirect_to_original_link'
end

app/models/link.rb
require 'digest/md5'

class Link < ActiveRecord::Base
  has_many :link_hits

  before_save :shortenize_link
  validates :original_link, url: true, presence: true
  validates :short_link, uniqueness: true

  def shortenize_link
    self.short_link = Digest::MD5.hexdigest(original_link)[0..5]<< Link.count.to_s #append uniq digits to differentiate links with same original link
  end
end

app/models/link_hit.rb
class LinkHit < ActiveRecord::Base
  belongs_to :link
  validates_presence_of :ip_address #could this be bad, if client browser is blocking ip_address?  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected 

  def current_ip
    request.remote_ip
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy, :redirect_to_original_link]

  def home_page
    @link = Link.new 
  end

  def index
    @links = Link.all.includes(:link_hits)
  end

  def show
    @link_hits = @link.link_hits
  end

  def redirect_to_original_link
    @link.link_hits.create(ip_address: current_ip)
    redirect_to @link.original_link 
  end

  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to show_link_path(@link.short_link), notice: "Link was successfully created! #{@link.original_link} has been shortened to #{request.env["HTTP_HOST"]}/#{@link.short_link}" }
        # format.json { render :show, status: :created, location: @link }
      else
        format.html { render :home_page }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_link
      @link = Link.find_by(short_link: params[:shortened_hash])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:short_link, :original_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Emasculate.ly</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>
              <a href="/links"> Links </a>
            </li>
          </ul>
      </div><!--/.navbar-collapse -->
    </div>
  </div>
   
  <div class="container" id="main-container">
    <%= yield %>
  </div>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for @link, html: { class:"form-inline" }  do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>
      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-lg-12">
      <div class="input-group">
      <%= f.text_field :original_link, class: "form-control", placeholder: "http://www.amazon.com/", autofocus: true %>
        <span class="input-group-btn">
          <%= f.submit "Shorten link" , class: "btn btn-info" %>
        </span>
      </div>
    </div>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/home_page.html.erb
<div class="jumbotron">
  <div class="container">
    <center>  
    <h1>Snip your link!</h1>
    <p><%= render 'form' %></p>
    </center>
  </div>
</div>
 
<div class="row">
  <div class="col-lg-12">
    <div class="page-header">
      <h1>About</h1>
    </div>
    <h4>Emasculate.ly is Bit.ly on steroids </h4>    
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="page-header">
      <h1>Contact</h1>
    </div>
  </div>
  <center> 
    <h4>Don't contact us </h4>    
    <%= image_tag "go-figure.jpg" %>
  </center>
  <hr class="invisible">
</div>

app/views/links/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Short Link</th>
      <th>Original Link</th>
      <th>Link Hits</th>
    </tr>
  </thead>
  <tbody>
  <% @links.each do |link| %>
    <tr>
      <td><%= link_to (root_url+link.short_link), "/#{link.short_link}", target: "_blank" %></td>
      <td><%= link.original_link %></td>
      <td><%= link_to link.link_hits.count.to_s + " hits", show_link_path(link.short_link) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Short link:</strong>
  <%= link_to (root_url+@link.short_link), "/#{@link.short_link}", target: "_blank" %>
</p>

<p>
  <strong>Original link:</strong>
  <%= link_to @link.original_link, @link.original_link, target: "_blank" %>
</p>

<p>
  <strong>Link hits:</strong>
  <%= @link_hits.count %>
</p>

<h3>Accessed from following IP addresses</h3>
<% @link_hits.each do |link_hit| %>
  <%= link_hit.ip_address %> - <%= time_ago_in_words(link_hit.created_at) %> ago <br />
<% end %>